apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-consumer
spec:
  selector:
    matchLabels:
      app: go-consumer
  template:
    metadata:
      labels:
        app: go-consumer
    spec:
      containers:
      - name: go-consumer
        image: robsantossilva/go-intensivo-fullcycle
        ports:
        - containerPort: 8080
